name: healthsync

services:
    webapp:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            # Environment variables for react
            PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8080}
            GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
        environment:
          # Environment variables for spring
          DATASOURCE_URL: jdbc:postgresql://db:5432/healthsync
          DATASOURCE_USER: healthsync
          DATASOURCE_PASSWORD: healthsync
          MAIL_USERNAME: ${MAIL_USERNAME}
          MAIL_PASSWORD: ${MAIL_PASSWORD}
          WEBAPP_BASEURL: ${PUBLIC_URL}

        restart: unless-stopped
        ports:
          - "8080:8080"

    db:
        image: postgres:14
        restart: unless-stopped
        environment:
          POSTGRES_USER: healthsync
          POSTGRES_PASSWORD: healthsync
          POSTGRES_DB: healthsync
        volumes:
          - db_data:/var/lib/postgresql/data
volumes:
  db_data:
